### ISSUE TITLE
Error on |start %canvas

### ISSUE THREAD

**Issue by timlucmiptev** [yosoyubik/canvas#3]
I put the full path to my ship's pier dir in `.urbitrc`, ran `npm run build`, and then boot up a moon. `%home` is mounted, I run `|commit %home`, and then `|start %canvas`. I get the following:

```
> |start %canvas
>=
activated app home/canvas
%cx /~ranbel-tacser-timluc-miptev/home/~2020.5.20..17.26.57..ffa7/app/canvas/hoon
scry failed for
ford: %hood failed for /~ranbel-tacser-timluc-miptev/home/0/app/canvas/hoon:
ford: %core on /~ranbel-tacser-timluc-miptev/home/0/app/canvas/hoon failed:
```

**Comment by yosoyubik** [comment]
What happens if you do `|start %canvas-view`? (maybe also check on the browser at `URL:PORT/~canvas`

**Comment by timlucmiptev** [comment]
OK, based on your comment and checking myself, I think the issue was that I in `.urbitrc` I used my ship's directory as the pier, rather than the mounted home dir. Think we can close this, my bad.
